config/routes.rb
Rails.application.routes.draw do
  resources :stages

  resources :statuses

  resources :appointments


  resources :patients

  resources :employees

  resources :physicians

  resources :diagnostics

  resources :insurances

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :diagnostic
  belongs_to :patient
  belongs_to :physician
  belongs_to :stage

  validate :appointmenttime, uniqueness: true

end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  has_many :appointments

  validates_presence_of :fee
  validate(:fee, :numericality => {:greater_than_equal_to => 0, :message => 'Fee cannot be negative'})
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base

  has_many :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments
  belongs_to :insurance
  has_many :physicians, through: :appointments
  has_one :user

  def fullname
    firstname + ' ' + lastname
  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appointments
  has_many :patients, through: :appointments




end

app/models/stage.rb
class Stage < ActiveRecord::Base

  has_many :appointments
end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:admin, :physician, :employee, :patient]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  belongs_to :patient

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @employees = Employee.all
    respond_with(@employees)
  end

  def show
    respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    respond_with(@employee)
  end

  def update
    @employee.update(employee_params)
    respond_with(@employee)
  end

  def destroy
    @employee.destroy
    respond_with(@employee)
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:firstname, :lastname, :address, :city, :state, :zip, :email)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @patients = Patient.all
    respond_with(@patients)
  end

  def show
    respond_with(@patient)
  end

  def new
    @patient = Patient.new
    respond_with(@patient)
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.save
    respond_with(@patient)
  end

  def update
    @patient.update(patient_params)
    respond_with(@patient)
  end

  def destroy
    @patient.destroy
    respond_with(@patient)
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:firstname, :lastname, :address, :city, :state, :zip, :phone, :email, :insurance_id, :insurancepolicynumber)
    end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @stages = Stage.all
    respond_with(@stages)
  end

  def show
    respond_with(@stage)
  end

  def new
    @stage = Stage.new
    respond_with(@stage)
  end

  def edit
  end

  def create
    @stage = Stage.new(stage_params)
    flash[:notice] = 'Stage was successfully created.' if @stage.save
    respond_with(@stage)
  end

  def update
    flash[:notice] = 'Stage was successfully updated.' if @stage.update(stage_params)
    respond_with(@stage)
  end

  def destroy
    @stage.destroy
    respond_with(@stage)
  end

  private
    def set_stage
      @stage = Stage.find(params[:id])
    end

    def stage_params
      params.require(:stage).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patient_view_helper.rb
module PatientViewHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing Employees</h1>

<table border="4" style="width:80%">
  <thead>
    <tr>
      <th> First Name </th>
      <th> Last Name </th>
      <th> Address </th>
      <th> City </th>
      <th> State </th>
      <th> Zip </th>
      <th> Email </th>
      <th colspan="3"> Actions </th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstname %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.address %></td>
        <td><%= employee.city %></td>
        <td><%= employee.state %></td>
        <td><%= employee.zip %></td>
        <td><%= employee.email %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @employee.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @employee.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>