config/routes.rb
Rails.application.routes.draw do
  resources :stages

  resources :statuses

  resources :appointments


  resources :patients

  resources :employees

  resources :physicians

  resources :diagnostics

  resources :insurances

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :diagnostic
  belongs_to :patient
  belongs_to :physician
  belongs_to :stage

  validate :appointmenttime, uniqueness: true

end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  has_many :appointments

  validates_presence_of :fee
  validate(:fee, :numericality => {:greater_than_equal_to => 0, :message => 'Fee cannot be negative'})
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base

  has_many :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments
  belongs_to :insurance
  has_many :physicians, through: :appointments
  has_one :user

  def fullname
    firstname + ' ' + lastname
  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appointments
  has_many :patients, through: :appointments




end

app/models/stage.rb
class Stage < ActiveRecord::Base

  has_many :appointments
end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:admin, :physician, :employee, :patient]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  belongs_to :patient

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @stages = Stage.all
    respond_with(@stages)
  end

  def show
    respond_with(@stage)
  end

  def new
    @stage = Stage.new
    respond_with(@stage)
  end

  def edit
  end

  def create
    @stage = Stage.new(stage_params)
    flash[:notice] = 'Stage was successfully created.' if @stage.save
    respond_with(@stage)
  end

  def update
    flash[:notice] = 'Stage was successfully updated.' if @stage.update(stage_params)
    respond_with(@stage)
  end

  def destroy
    @stage.destroy
    respond_with(@stage)
  end

  private
    def set_stage
      @stage = Stage.find(params[:id])
    end

    def stage_params
      params.require(:stage).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patient_view_helper.rb
module PatientViewHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing Statuses</h1>

<table border="4" style="width:30%">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>