config/routes.rb
Rails.application.routes.draw do
  resources :stages

  resources :statuses

  resources :appointments


  resources :patients

  resources :employees

  resources :physicians

  resources :diagnostics

  resources :insurances

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :diagnostic
  belongs_to :patient
  belongs_to :physician
  belongs_to :stage

  validate :appointmenttime, uniqueness: true

end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base

  has_many :appointments

  validates_presence_of :fee
  validate(:fee, :numericality => {:greater_than_equal_to => 0, :message => 'Fee cannot be negative'})
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base

  has_many :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments
  belongs_to :insurance
  has_many :physicians, through: :appointments
  has_one :user

  def fullname
    firstname + ' ' + lastname
  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appointments
  has_many :patients, through: :appointments




end

app/models/stage.rb
class Stage < ActiveRecord::Base

  has_many :appointments
end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:admin, :physician, :employee, :patient]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  belongs_to :patient

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patient_view_helper.rb
module PatientViewHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div align = "right"  class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <% if user_signed_in? %>

              <%= link_to 'Patients', new_patient_path, class: 'navbar-brand' %>
              <%= link_to 'Appointments', new_appointment_path, class: 'navbar-brand' %>

      <% else %>

      <%= link_to 'Appointments', appointments_path, class: 'navbar-brand' %>
      <%= link_to 'Physicians', physicians_path, class: 'navbar-brand' %>
      <%= link_to 'Patients', patients_path, class: 'navbar-brand' %>
      <%= link_to 'Diagnostics', diagnostics_path, class: 'navbar-brand' %>

      <% end %>



    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li align = "right" ><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li align = "right" ><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li align = "right" ><%= link_to 'Sign in', new_user_session_path %></li>
  <li align = "right" ><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li align = "right" ><%= link_to 'Admin', '/admin' %></li>
    <li align = "right" ><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DC Houston" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "DC Houston" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <title>jQuery UI Datepicker - Default functionality</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script>
        $(function() {
            $( "#idname" ).datetimepicker();
        });
    </script>

  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>

    </main>
  </body>
</html>